version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
