version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"   # Web UI
      - "4317:4317"     # OTLP/gRPC (for OpenTelemetry SDKs)
      - "4318:4318"     # OTLP/HTTP (optional)
      - "14250:14250"   # gRPC for collector
      - "6831:6831/udp" # UDP for traces (Thrift)
    networks:
      - devnet

networks:
  devnet:
    external: true
