global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"] # For node_exporter or system metrics

  # Example: Node.js app exposing /metrics
  - job_name: "nodejs-app"
    static_configs:
      - targets: ["host.docker.internal:3001"] # Replace with your app's metrics port

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
