version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # for RabbitMQ client (AMQP)
      - "15672:15672" # for Web UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
