version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    ports:
      - "8500:8500"      # Web UI & HTTP API
      - "8600:8600/udp"  # DNS
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - ./data:/consul/data
