version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
