version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
    networks:
      - devnet

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"  # RedisInsight UI
    networks:
      - devnet
    depends_on:
      - redis

networks:
  devnet:
    driver: bridge
